export const getDetailedRejectionReason = (reasonStr) => {
    const r = (reasonStr || "").toLowerCase();
    let detailed = "";
    
    if (r.includes('age')) {
        detailed = `Application Rejected due to Age Criteria: The applicant's current age falls outside the lender's mandatory age brackets for unsecured lending. Banks enforce strict age policies to ensure the applicant has sufficient professional experience, stable income, and a long enough working life to comfortably repay the loan without financial distress.\n\nNext Steps & Precautions: Unfortunately, age is a hard parameter set by the bank's central risk committee. If you are underage, you will need to wait until you meet the minimum threshold. Alternatively, you can apply with a co-applicant (such as a parent or older business partner/spouse) who meets the age criteria to bypass this restriction.`;
    } else if (r.includes('foir') || r.includes('emi exceeds')) {
        detailed = `Application Rejected due to High FOIR (Fixed Obligation to Income Ratio): Your current EMI obligations consume too much of your monthly income. Banks calculate FOIR to ensure you have enough disposable income left for living expenses after paying all your EMIs. Exceeding the FOIR limit indicates a high risk of default or financial strain.\n\nNext Steps & Precautions: To improve your eligibility, you must reduce your current monthly obligations. You can achieve this by foreclosing smaller existing loans, clearing outstanding credit card dues, or applying for a Balance Transfer (BT) to consolidate your existing high-interest debt into a single, longer-tenure loan with a lower EMI. You may also add a co-applicant with a stable income to increase your combined FOIR capacity.`;
    } else if (r.includes('vintage') || r.includes('history') || r.includes('statement period')) {
        detailed = `Application Rejected due to Insufficient Vintage/Operational History: The applicant's business, employment history, or bank statement duration is too short to meet this specific lender's minimum requirements. Banks require a proven track record (typically 2-3 years) to assess long-term sustainability and survival rate before extending unsecured credit.\n\nNext Steps & Precautions: We recommend maintaining clean banking, GST, and ITR records for the current financial year to build your vintage organically. Do not apply to other top-tier banks immediately, as it will cause unnecessary CIBIL hits. In the meantime, you may explore alternative Tier-2 lenders or NBFCs on our platform who accept lower vintage profiles, or consider securing a collateral-backed loan which has significantly relaxed vintage requirements.`;
    } else if (r.includes('cibil') || r.includes('-1')) {
        detailed = `Application Rejected due to CIBIL Score Profile: The applicant's CIBIL score does not meet the lender's minimum threshold, or the profile is completely new to credit (Score -1/0). A low or absent credit score suggests either past repayment issues or a lack of proven credit history, making the profile too risky for this specific institution.\n\nNext Steps & Precautions: If you have a -1 score, begin building credit by taking a small consumer durable loan or a secured credit card against an FD. Ensure 100% on-time payments for at least 6 months. If your score is low due to past defaults, you must clear those overdue amounts immediately, wait for your score to refresh, and strictly avoid applying for any new unsecured loans, as each rejection inquiry will drop your score further.`;
    } else if (r.includes('utilisation') || r.includes('limit') || r.includes('cap')) {
        detailed = `Application Rejected due to Excessive Limit Utilisation: The applicant is heavily utilizing their existing credit lines (Credit Cards or Overdrafts). Banks view consistently high limit utilization (usually above 80%) as a sign of 'credit hunger' and severe cash flow stress, significantly increasing the probability of default.\n\nNext Steps & Precautions: You must urgently bring your credit card and OD utilization below 50% of your sanctioned limit before reapplying. Pay down the balances before the statement generation date. Over-utilization directly damages your CIBIL score month-on-month. Once the limits are paid down and reported to the bureau, your profile risk will downgrade, and you can re-initiate the loan application.`;
    } else if (r.includes('entries') || r.includes('debit/credit')) {
        detailed = `Application Rejected due to Low Transaction Density: The bank statement provided does not show enough business activity (credit/debit entries) to satisfy the lender's criteria. Banks analyze transaction volume to verify that the business is actively trading and generating consistent, verifiable cash flow to support the proposed EMI.\n\nNext Steps & Precautions: This usually happens if primary business transactions are done in cash or routed through a different unlinked account. Please ensure that all your business revenues are routed digitally through your primary current account. If you have another current account with higher transaction density, please upload that statement instead for a re-evaluation.`;
    } else if (r.includes('salary') || r.includes('bto') || r.includes('turnover') || r.includes('threshold')) {
        detailed = `Application Rejected due to Income/Turnover Requirements: The applicant's declared income or Business Turnover (BTO) falls below the lender's mandatory minimum threshold for this specific loan product or category. Banks enforce rigid income minimums to ensure the applicant has the fundamental financial capacity to service a new loan.\n\nNext Steps & Precautions: Do not apply to premium banks that have high minimum income cutoffs. You can increase your eligibility by adding a working co-applicant (spouse, parent, or partner) to combine your incomes. Alternatively, our engine will automatically match you with NBFCs and Tier-2 banks that cater specifically to lower-income or lower-turnover brackets.`;
    } else if (r.includes('multiplier')) {
        detailed = `Application Rejected due to Multiplier Constraints: Your profile category and income do not generate a high enough multiplier to satisfy the minimum loan amount required, or the bank's specific multiplier matrix for your employer category is highly restricted.\n\nNext Steps & Precautions: Multipliers are heavily dependent on your employer's categorization (e.g., CAT A/B/C). If your company is unlisted, the bank applies a severe haircut to your eligibility. To improve this, you can apply for a Balance Transfer (BT) to remove existing debts from the equation, or pivot your application to a lender that focuses purely on FOIR rather than strict corporate categorization multipliers.`;
    } else if (r.includes('gst') || r.includes('itr')) {
        detailed = `Application Rejected due to GST/ITR Documentation Rules: The applicant failed the lender's strict GST or Income Tax Return (ITR) validation rules. The lender may require a longer history of filed returns, or specific details (like Firm Name) were missing from the ITR document, making the income unverified as per their internal policy.\n\nNext Steps & Precautions: Ensure that your Chartered Accountant always includes your exact Firm Name in your ITR filings, as many premium banks auto-reject applications without it. If your GST is relatively new, wait until it crosses the 2 or 3-year mark before applying to Tier-1 banks. In the meantime, we can route your application to lenders who operate purely on Bank Statement Analysis (Banking Surrogate) without requiring GST.`;
    } else if (r.includes('rented')) {
        detailed = `Application Rejected due to Residence/Office Ownership: The lender's policy strictly prohibits lending to profiles where both the residence and office are rented. Banks use property ownership as a proxy for stability; 'double rented' profiles are categorized as high flight risks.\n\nNext Steps & Precautions: If you own property in another city, or if a blood relative owns the property you live in, provide that proof to override this rejection. Otherwise, you must exclusively target NBFCs and lenders who specialize in 'double rented' profiles, though you should expect slightly higher interest rates as a risk premium.`;
    } else {
        detailed = `Application Rejected due to Internal Policy Parameters: The applicant's profile did not clear the bank's internal algorithmic risk matrices. The rejection could be due to a combination of factors including location restrictions (geo-limits), employer categorization, or complex banking behavior flags detected during statement analysis.\n\nNext Steps & Precautions: We strongly advise against making further blind applications to other banks, as this will trigger multiple hard CIBIL inquiries and severely damage your credit score. Review your bank statements for any hidden liabilities, bounce charges, or high credit card utilization. Our platform's alternative lenders may still offer you a customized loan product based on your current metrics.`;
    }
    
    // Prepend the exact system reason for reference
    return `[System Log: ${reasonStr}]\n\n${detailed}`;
};
